site_name: Web de Sergio
site_url: https://serpemorales.github.io

theme:
  name: material

nav:
  - Home: index.md
  - DAW:
      - Práctica 2.1: practica2_1/index.md
      - Práctica 2.2: practica2_2/index.md
      - Práctica 2.3: practica2_3/index.md
      - Práctica 2.4: practica2_4/index.md
      - Práctica 2.5: practica2_5/index.md

